services:
  mermaid-render-mcp:
    image: mermaid-render-mcp:latest
    container_name: mermaid-render-mcp
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - /dev/shm:/dev/shm
    security_opt:
      - seccomp:unconfined
